### PR TITLE
Updating firmware to latest.

### PR DESCRIPTION
**Pull request by f1vefour**
Have a look at this and make sure it's okay to merge, I tested the firmware and all seems good. This package needs updated weekly.

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Can you make it a package suitable for our autobuild scripts? Look at the new lirc repo as an simple example.

**Comment by f1vefour** [comment]
What are these automated packages built using, what backend? I need to see some documentation CurlyMo, using the lirc isn't really an option because it's building from source. We just need a simple package that pulls from the Raspberry firmware git and packages binaries.

**Comment by CurlyMoo** [comment]
This is a "pull from git" example:
https://github.com/xbianonpi/xbian-package-kernel/blob/master/build/rpi/config

**Comment by f1vefour** [comment]
Your not answering me though, what is the context? What are you building these with?

**Comment by CurlyMoo** [comment]
https://github.com/xbianonpi/xbian/wiki/Building-XBian-IMAGES
https://github.com/xbianonpi/xbian/wiki/Building-XBian-packages

**Comment by f1vefour** [comment]
Let me reword myself. What is pulling and building these automated packages?

**Comment by CurlyMoo** [comment]
Just for the crew :smile: The last server here: http://forum.xbian.org/thread-2682.html

**Comment by f1vefour** [comment]
I posted in the thread, you can respond by email or PM.

**Comment by f1vefour** [comment]
I will work on an automated build for the firmware, it's super important it stays up to date.

**Comment by mk01** [comment]
@f1vefour 

create simple structure from any package configuration converted already to $xbiangit. as content-tpl use what is currently in xbian-package-firmware/content/DEBIAN.

as "config_source_type" use "git", point to github/raspberry/firmware, set to clean after run (or not - doesn't matter). 

as build "config_build_make" use "true" (which is dumb command returning 0), "config_build_targets" "" (empty). install_target empty too. 

so up to now very easy to prepare. then as actual "install" step create hook.d/post-inst.d script which will copy files we need (we copy manually today). that's all.

**Comment by mkreisl** [comment]
Is this version here up2date? Probably not, version here is 2.0.3 and current repo-version is 2.2.0.
Kernel 4.1.3 requires the latest firmware version, so it would be a good time to make a rework of this package

**Comment by mkreisl** [comment]
Done

**Pull request closed without merging**
